sudo: false
language: c

matrix:
  include:
    - os: osx
      osx_image: xcode8
      compiler: clang
      env:
        - MATRIX_EVAL="true"

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="true"

    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env:
        - MATRIX_EVAL="true"

    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install gcc@8 && CC=gcc-8 && CXX=g++-8"

addons:
  homebrew:
    update: true
    packages:
      - python@3

install:
  - eval "${MATRIX_EVAL}"
  - export PATH=$(brew --prefix llvm)/bin:$PATH

script:
  - export CODEBUILD_SRC_DIR=$(pwd)
  - python3 ./codebuild/builder.py build macos-default-default-macos-x64
